### PR TITLE
Issue 430: Generate OperationDefinitions for named queries, fix minor…

### LINKED ISSUE #430: DSTU3 - The named query (search) does not been generated in ServerConformanceProvider
Hello,
   I found that the advanced query which was defined by named query - "@Search(name=xxx)" does not been generated in ServerConformanceProvider.
  http://www.hl7.org/implement/standards/fhir/search.html#advanced, the official document said that "Servers can define their own additional named queries to meet their own uses using an OperationDefinition.", So when there are named queries used in resource providers, then the metadata should generate the OperationDefinition like as the "@Operation" if I understood correctly.
   @jamesagnew, can you check that?

### PR DESCRIPTION
**Pull request by srdo**
… errors in generation of OperationDefinition for operations. Closes #430.

See #430

This fixes the following issues:

* Generate OperationDefinition for named queries. Added tests for queries at type level and at server level.
* Fix potential NPE in BaseMethodBinding when the method return type is a raw typed collection.
* When an operation appears at system level with no IdType parameter, the generated definition specified that the operation could be invoked at both system and type level.

### CODE REVIEW

File: hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/OperationMethodBinding.java [hunk 1]
```diff
@@ -141,14 +142,9 @@ protected OperationMethodBinding(Class<?> theReturnResourceType, Class<? extends
...
-
-		if (myIdParamIndex != null) {
-			myCanOperateAtInstanceLevel = true;
-		}
-		if (getResourceName() == null) {
-			myCanOperateAtServerLevel = true;
-		}
-
+    
+    myCanOperateAtTypeLevel = true;
```
Comment (srdo) [inline hapi-fhir-server/src/main/java/ca/uhn/fhir/rest/server/method/OperationMethodBinding.java]: Whoops. this is left over from debugging. I'll remove it shortly.

**Comment by srdo** [comment]
Is the failing test flaky? It doesn't look related to my changes, and is passing in the appveyor build. The test passes when I build locally.

File: hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java [hunk 2]
```diff
@@ -621,6 +637,120 @@ public void testValidateGeneratedStatement() throws Exception {
...
+		ourLog.info(conf);
+
+    List<CapabilityStatementRestOperationComponent> operations = conformance.getRest().get(0).getOperation();
+		assertThat(operations.size(), is(1));
+		assertThat(operations.get(0).getName(), is(TypeLevelOperationProvider.OPERATION_NAME));
+
+		OperationDefinition opDef = sc.readOperationDefinition(new IdType(operations.get(0).getDefinition().getReference()));
+		validate(opDef);
+		assertEquals(TypeLevelOperationProvider.OPERATION_NAME, opDef.getCode());
+    assertThat(opDef.getSystem(), is(false));
```
Comment (Sheepyhead) [inline hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java]: Fix the wonky indentation

File: hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java [hunk 3]
```diff
@@ -344,6 +356,10 @@ public CapabilityStatement getServerConformance(HttpServletRequest theRequest) {
 		assertEquals("1", opDef.getParameter().get(2).getMinElement().getValueAsString());
 		assertEquals("2", opDef.getParameter().get(2).getMaxElement().getValueAsString());
 		assertEquals("string", opDef.getParameter().get(2).getTypeElement().getValueAsString());
+    
+    assertThat(opDef.getSystem(), is(true));
```
Comment (Sheepyhead) [inline hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java]: Fix the wonky indentation

File: hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java [hunk 4]
```diff
@@ -124,6 +133,9 @@ public void testExtendedOperationReturningBundle() throws Exception {
 		OperationDefinition opDef = sc.readOperationDefinition(new IdType("OperationDefinition/Patient-i-everything"));
 		validate(opDef);
 		assertEquals("everything", opDef.getCode());
+    assertThat(opDef.getSystem(), is(false));
```
Comment (Sheepyhead) [inline hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java]: Fix the wonky indentation

File: hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java [hunk 5]
```diff
@@ -621,6 +637,120 @@ public void testValidateGeneratedStatement() throws Exception {
...
+    assertThat(param.getSearchTypeElement().asStringValue(), is(RestSearchParameterTypeEnum.QUANTITY.getCode()));
+    assertThat(param.getMin(), is(1));
+    assertThat(param.getMax(), is("1"));
+    assertThat(param.getUse(), is(OperationParameterUse.IN));
+  }
+  
+  @Test
+  public void testResourceLevelNamedQueryWithParameters() throws Exception {
+    RestfulServer rs = new RestfulServer(ourCtx);
+		rs.setProviders(new NamedQueryResourceProvider());
```
Comment (Sheepyhead) [inline hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java]: Weird indentation

File: hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java (hunk 2 above)
Comment (srdo) [reply hapi-fhir-structures-dstu3/src/test/java/org/hl7/fhir/dstu3/hapi/rest/server/ServerCapabilityStatementProviderDstu3Test.java]: Will do. The project seems to use a mix of tabs and spaces, and also a mix of indentation levels, which is why it only looks weird in some places.
