### PR TITLE
Several JPA search fixes

### LINKED ISSUE #1188: Occurrence parameter not working on CommunicationRequest & ProcedureRequest on DSTU3
We have created  couple of CommunicationRequests on the Hapi Server and we are trying to fetch them using the occurrence parameter

The resources created are:
http://hapi.fhir.org/baseDstu3/CommunicationRequest/fm-solicit

The url we are trying to fetch them using the url:
http://hapi.fhir.org/baseDstu3/CommunicationRequest?occurrence=ge2015-08-10T11:33:00-04:00

It seems that the occurrence parameter works if the occurrenceDateTime is used but if occurrencePeriod/occurrenceTiming is used it does not 

Thanks
Ravi Kuchi

### LINKED ISSUE #1223: multiple identifier search does not work
Hello All,

In HAPI FHIR 3.6 this worked
http://hapi.fhir.org/baseDstu3/Organization?identifier=FDS-BusinessId%7C965214&identifier=2.16.840.1.113883.3.79%7C1000005
returned Bundle with 1 result

In HAPI FHIR 3.7 Bundle with 0 result
Was there a change in the spec or is there a bug?

Thanks,

### PR DESCRIPTION
**Pull request by jamesagnew**
Fixes #1188 
Fixes #1223

### CODE REVIEW

**Comment by jamesagnew** [comment]
@fil512 Code review please.

This change fixes the "double identifier search not working".. And I've also added some utility methods for logging generated SQL statements in hopefully a more helpful way. See `FhirResourceDaoR4SearchNoFtTest#testSearchOnPeriod()` for an example.

**Comment by jamesagnew** [comment]
Oops- Sorry @fil512 , looks like a few tests are failing actually. Maybe hold off.

**Comment by jamesagnew** [comment]
@fil512 this is ready now

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/config/CaptureQueriesListener.java [hunk 1]
```diff
@@ -1,92 +1,103 @@
...
+			.collect(Collectors.toList());
+	}
 
+	/**
+	 * Returns all INSERT queries executed on the current thread - Index 0 is oldest
+	 */
+	public static List<Query> getInsertQueriesForCurrentThread() {
+		return getCapturedQueries()
+			.stream()
+			.filter(t -> t.getThreadName().equals(Thread.currentThread().getName()))
```
Comment (fil512) [inline hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/config/CaptureQueriesListener.java]: There's a chance this could lead to intermittent test failures down the road (if a log of sql happens in another thread during your test) but probably fine to just wait and see if it's ever a problem.

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/config/CaptureQueriesListener.java [hunk 2]
```diff
@@ -1,92 +1,103 @@
...
+ * <p>
+ * Note that this class is really only designed for use in testing - It adds a non-trivial overhead
+ * to each query.
+ * </p>
+ */
+public class CaptureQueriesListener extends BaseCaptureQueriesListener {
 
-	private static final LinkedList<Query> LAST_N_QUERIES = new LinkedList<>();
+	private static final int CAPACITY = 100;
+	private static final Queue<Query> LAST_N_QUERIES = Queues.synchronizedQueue(new CircularFifoQueue<>(CAPACITY));
```
[the remark this answers is not in the document]
Comment (jamesagnew) [reply hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/config/CaptureQueriesListener.java]: Yeah probably a good call. Done.

File: hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/config/CaptureQueriesListener.java (hunk 1 above)
Comment (jamesagnew) [reply hapi-fhir-jpaserver-base/src/test/java/ca/uhn/fhir/jpa/config/CaptureQueriesListener.java]: Yeah, this is definitely a real (though I believe fairly remote) possibility.

Thinking about it maybe I'll increase the buffer a bit (it currently stores 100 queries and resets during every test but storing these queries should be very memory-cheap so there is no reason not to keep 1000).

Maybe a future enhancement could be for a test to lock the thing to only capture a specific thread's queries.
